In [3]:
import pandas as pd
df = pd.read_csv("~/notes/CS-py/CS107/files/Party-words.csv")
df

   Several  Few  Many  Couple  Dozens  Some  Score
0        5    5    10       4      12    15     25
1        5    3    12       2      24     4     35

## Adding Rows and Columns to Dataframe  

create a new column in df called "Many+4" with a value 4 larger than the origianl value in the column "Many"

In [5]:
df["Many+4"] = df["Many"]+4
df

   Several  Few  Many  Couple  Dozens  Some  Score  Many+4
0        5    5    10       4      12    15     25      14
1        5    3    12       2      24     4     35      16

adding a new row to a DataFrame using loc; we need to specify the name and a dictionary of values

In [8]:
df.loc["Extra Row"] = {"Many":1000}
df

           Several  Few  Many  Couple  Dozens  Some  Score  Many+4
0              5.0  5.0    10     4.0    12.0  15.0   25.0    14.0
1              5.0  3.0    12     2.0    24.0   4.0   35.0    16.0
Extra Row      NaN  NaN  1000     NaN     NaN   NaN    NaN     NaN